Add infix operator expression number of items multiline formatter
fsprojects/fantomas pull request #1177
Opened 2020-09-29 22:57 UTC by Fizzixnerd

See https://github.com/fsprojects/fantomas/issues/1143.

Final change from the above issue.  I'm thinking that getting the basic functionality in and then refining it as needed over time is probably the best course of action; the current code gives the strange results I mentioned in the above issues when involving mathematical operators, but so can the `CharacterWidth` formatter, so I don't think it's introducing anything worse.  Let me know what you think.

2020-10-02 08:45 UTC, nojaf commented
Hey @Fizzixnerd, I finally found some time to take a look at this PR. The code looks OK but I'm not convinced of this setting to be honest.

Tests like
```fsharp
[<Test>]
let ``mathematical expressions`` () =
    formatSourceString false """
let w = x + y + z
let w = x - y - z
    """ config
    |> prepend newline
    |> should equal """
let w =
    x
    + y
    + z
let w =
    x
    - y
    - z
"""
```

seem to contract the original text in the feature request (#1143).

So I like to take a step back and go return to the drawing board here.
What problem are we trying to fix here?
If you format your codebase today with latest stable Fantomas. What results are not satisfying?
Maybe we could come up with something that only impacts the [newLineInfixOps](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/Context.fs#L939).

2020-10-03 20:44 UTC, Fizzixnerd commented
> Hey @Fizzixnerd, I finally found some time to take a look at this PR. The code looks OK but I'm not convinced of this setting to be honest.

Looking back, I'm in agreement.

> Tests like
> 
> ```fsharp
> [<Test>]
> let ``mathematical expressions`` () =
>     formatSourceString false """
> let w = x + y + z
> let w = x - y - z
>     """ config
>     |> prepend newline
>     |> should equal """
> let w =
>     x
>     + y
>     + z
> let w =
>     x
>     - y
>     - z
> """
> ```
> 
> seem to contract the original text in the feature request (#1143).

Yes.

> So I like to take a step back and go return to the drawing board here.
> What problem are we trying to fix here?
> If you format your codebase today with latest stable Fantomas. What results are not satisfying?
> Maybe we could come up with something that only impacts the [newLineInfixOps](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/Context.fs#L939).

Problems:
- Expressions such as
  ```fsharp
  x |> f |> g |> h
  
  ys
  |> List.choose (fun y -> if y = 3 then Ok y else None)
  ```
  Are undesirable to us.  We would prefer
  ```fsharp
  x
  |> f
  |> g
  |> h

  ys |> List.choose (fun y -> if y = 3 then Ok y else None)
  ```
  In short: for pipeline-like operators we want multiline after `n` operators, and single line for `n` and less.  I'm currently leaning on `n = 2` in this case, though that's a detail that I think is not so important.

- Expressions such as
  ```fsharp
  w + x + y - z
  ```
  We want to remain single line as much as possible.

Best option, I think, is to do as your suggest with the newLineInfixOps, and leave the normal behavior for everything else.  I will make a change and try it out on our internal test code.

2020-10-03 23:06 UTC, Fizzixnerd commented
Looking at the tests and the internal code we are using to trial Fantomas, I think the latest changes properly solve the problem we were having.  I have changed the names of the config options to reflect their new purpose.

2020-10-10 09:24 UTC, nojaf requested changes
Hey @Fizzixnerd,
Apologies for the slow response, I've been preoccupied with other life I'm afraid.
The PR looks good yet I would like to emphasis that this only impact those few newline infix operators. In some places, I still found a bit of mix, so I'd like you to clear those up.

2020-10-10 09:24 UTC, nojaf commented on docs/Documentation.md
>  ### fsharp_max_infix_operator_expression
Would it not be easier to understand if this setting doesn't apply for the newline infix operators?
Then you don't need to have any `*_multiline_formatter` setting in place and the default behaviour sorta is respected.

2020-10-10 09:24 UTC, nojaf commented on docs/Documentation.md
> +`{ defaultConfig with MaxNewlineInfixOperatorExpressionNumberOfItems = 2; NewlineInfixOperatorExpressionMultilineFormatter = 2 }`
`NewlineInfixOperatorExpressionMultilineFormatter = 2` should be `NewlineInfixOperatorExpressionMultilineFormatter  = NumberOfItems` here right? Or am I missing something?

2020-10-10 09:24 UTC, nojaf commented on src/Fantomas.Tests/NumberOfItemsInfixOperatorExpressionTests.fs
> +module Fantomas.Tests.NumberOfItemsInfixOperatorExpressionTests
MultilineInfixOperators*

2020-10-10 09:24 UTC, nojaf commented on src/Fantomas/CodePrinter.fs
> +            let size =
Does this not miss any further check whether the infix operator is a multiline one?

2020-10-10 09:24 UTC, nojaf commented on src/Fantomas.Tests/NumberOfItemsInfixOperatorExpressionTests.fs
> +            Math.Sin(deg2rad (latA)) * Math.Sin(deg2rad (latB))
This doesn't seem correct to me, `Math.Sin(deg2rad (latA)) * Math.Sin(deg2rad (latB))` does not have any newline infix involved and is over 50 characters long.
![image](https://user-images.githubusercontent.com/2621499/95651400-76ff4d00-0aea-11eb-822f-8264d4e22bb9.png)

2020-10-10 09:24 UTC, nojaf commented on src/Fantomas.Tests/NumberOfItemsInfixOperatorExpressionTests.fs
> +    (Regex.Matches(line, regex).Count - Regex.Matches(line, "\\\\" + regex).Count) % 2 = 1
`(Regex.Matches(line, regex).Count - Regex.Matches(line, "\\\\" + regex).Count)` should be split here I think.

2020-10-10 09:24 UTC, nojaf commented on src/Fantomas.Tests/NumberOfItemsInfixOperatorExpressionTests.fs
> +    aaaaaaaaaaaaaaaaaaaaaaaa * bbbbbbbbbbbbbbbbbbbbbbbbb
`aaaaaaaaaaaaaaaaaaaaaaaa * bbbbbbbbbbbbbbbbbbbbbbbbb` should be split here.

2020-10-23 14:21 UTC, merged

2020-10-23 14:23 UTC, nojaf commented
Hey @Fizzixnerd, I took the liberty of completing this PR. We can still discuss things if you like to.
I made some minor changes and added a tad more focus that the settings only impacts those multiline infix operators. 
I'll release an alpha shortly so you can try it out.

2020-10-23 15:34 UTC, Fizzixnerd commented
Hey @nojaf, thanks for that, I have been really busy and was trying to find the time on the weekend but just couldn't.  Sorry about that.

2020-10-23 15:55 UTC, nojaf commented
No worries, I totally get that. You can try the changes in https://www.nuget.org/packages/fantomas-tool/4.3.0-alpha-001.

2020-11-02 16:38 UTC, Fizzixnerd commented
Hi @nojaf, I think I found a couple of issues. Will try to clean them up into a simple repro tonight, but just giving a heads up.

2020-11-06 08:25 UTC, nojaf commented
Hey @Fizzixnerd, any luck with reproducing those issues?
And did you see my comment in https://github.com/fsprojects/fantomas/issues/1143#issuecomment-719666763
I'm waiting to release 4.3 stable until we got everything sorted out of you PRs, so could you take a look at this?
Thanks!