Option to reduce multiple blank lines from source code
fsprojects/fantomas pull request #2243
Opened 2022-05-10 20:15 UTC by jindraivanek

Fix #2198.

Introduce new config option `KeepMaxBlankLines` that set maximal number of consecutive blank lines from source code that is kept in formatted code.

I'm open to suggestion to better name for new option.

Option is now implemented as a number, with big value as default. Is it OK, or it should be `Num option`?

`KeepMaxBlankLines=0` reveals multiple cases where Fantomas should add blank lines - I think this should be solved as separate issue(s).

Checklist:
- [ ] agree on name of new option
- [ ] new option: `Num` or `Num option`?

2022-05-11 09:24 UTC, nojaf requested changes
This looks good! I've added one remark in terms of creating the Newline trivia, that might be an interesting one to consider. Otherwise, a couple of nits but nothing serious.

I would also like to see the edge cases here. I wasn't able to see the limitations that `fsharp_keep_max_blank_lines=0` has.
We could have this as an ignored test to highlight we are at least aware of when this will do weird things.

Well done!

2022-05-11 09:24 UTC, nojaf commented on docs/Documentation.md
> +fsharp_keep_max_blank_lines=100
Maybe go for `fsharp_keep_max_number_of_blank_lines`.
We used `number_of_` before. But I don't have a strong opinion on it.
`fsharp_keep_max_blank_lines` would work for me as well.

2022-05-11 09:24 UTC, nojaf commented on src/Fantomas.Core.Tests/TestHelpers.fs
> +let checkFormat config source expected =
Could you move this to `KeepMaxEmptyLinesTests`? It is only used there and I typically want to keep all the tests having the same structure.
This is ok to have, just make it clear that it is only used for `KeepMaxEmptyLines`.

2022-05-11 09:24 UTC, nojaf commented on src/Fantomas.Core.Tests/TestHelpers.fs
> +let checkFormat config source expected =
Could you move this to `KeepMaxEmptyLinesTests`? It is only used there and I typically want to keep all the tests having the same structure.
This is ok to have, just make it clear that it is only used for `KeepMaxEmptyLines`.

2022-05-11 09:24 UTC, nojaf commented on src/Fantomas.Core.Tests/KeepMaxEmptyLinesTests.fs
> +﻿module Fantomas.Core.Tests.KeepMaxEmptyLines
Rename to `module Fantomas.Core.Tests.KeepMaxEmptyLinesTests`

2022-05-11 09:24 UTC, nojaf commented on src/Fantomas.Core.Tests/KeepMaxEmptyLinesTests.fs
> +﻿module Fantomas.Core.Tests.KeepMaxEmptyLines
Rename to `module Fantomas.Core.Tests.KeepMaxEmptyLinesTests`

2022-05-11 09:24 UTC, nojaf commented on src/Fantomas.Core/FormatConfig.fs
> +      KeepMaxBlankLines: Num
I would go for `Num` here, `Num option` was never used and looks unnecessary.

2022-05-11 09:24 UTC, nojaf commented on src/Fantomas.Core/FormatConfig.fs
> +      KeepMaxBlankLines: Num
I would go for `Num` here, `Num option` was never used and looks unnecessary.

2022-05-11 09:24 UTC, nojaf commented on src/Fantomas.Core/Trivia.fs
> +            let numberOfNewlinesAtEndOfContent triviaContent =
I wonder if we could not collect the newlines in the first place in `collectTriviaFromBlankLines` if we know there is a limit.

If we detected a newline at lines `[ 2; 3; 5]` and the limit is 1, we could potentially only create two Newline trivia `[ Newline at 3; Newline at 5 ]`.
I'm not sure what would be more performant.

2022-05-11 09:24 UTC, nojaf commented on src/Fantomas.Core/Trivia.fs
> +            let numberOfNewlinesAtEndOfContent triviaContent =
I wonder if we could not collect the newlines in the first place in `collectTriviaFromBlankLines` if we know there is a limit.

If we detected a newline at lines `[ 2; 3; 5]` and the limit is 1, we could potentially only create two Newline trivia `[ Newline at 3; Newline at 5 ]`.
I'm not sure what would be more performant.

2022-05-11 11:42 UTC, jindraivanek commented
> I would also like to see the edge cases here. I wasn't able to see the limitations that `fsharp_keep_max_blank_lines=0` has.
> We could have this as an ignored test to highlight we are at least aware of when this will do weird things.

It can be seen from my experiment here https://github.com/fsprojects/fantomas/issues/2198#issuecomment-1097272001 (it was POC, but result should be same - I try to reproduce same thing with this implementation later).

I will create ignored test highlighting problematic case from this.

2022-05-11 12:30 UTC, nojaf commented
> but result should be same

I'm not entirely sure about that, because this time, less trivia was assigned to a trivia node and I believe in the original POC the newlines were swallowed in CodePrinter.
So I'm not sure if you can still have the weird behaviour.

2022-05-11 20:43 UTC, jindraivanek commented
I made requested changes.

Fantomas.Core formatted with fsharp_keep_max_number_of_blank_lines=0 is here: https://github.com/jindraivanek/fantomas/commit/ece950fb35d2ae7544c16de0c778cc72e8a1dbde

Only thing missing is ignored test(s) with problematic cases from there.

2022-05-12 06:40 UTC, nojaf approved these changes
Spot on! Thank you.

2022-05-12 06:50 UTC, merged